FROM alpine

ENV TZ=Asia/Shanghai

RUN apk add --no-cache tzdata ca-certificates curl && \
    rm -rf /var/cache/apk/* &&\
    mkdir -p /app

ARG TARGET_ARCH

COPY dist/BestSub_linux_${TARGET_ARCH}/BestSub /app/BestSub

CMD /app/BestSub
